<?php

namespace Xiaosongshu;

use PHPUnit\Framework\TestCase;
use Xiaosongshu\Admin\Client;

class Test extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public  function testTalk(){
        $res = Client::talk();
        self::assertIsArray($res);
        self::assertArrayHasKey('status',$res);
        self::assertEquals(201,$res['status']);
        self::assertEquals('ok1',$res['msg']);
    }
}